language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

services:
  - docker

before_install:
  - docker run -d -p 4572:4572 -p 4569:4569 -e SERVICES=dynamodb,s3  localstack/localstack

script: make build verify