language: go

go:
  - 1.12.x

#need fake aws credentials as verification is run against localstack
env:
  - GO111MODULE=on
  - AWS_ACCESS_KEY_ID=foobar
  - AWS_SECRET_ACCESS_KEY=foobar

services:
  - docker

before_install:
  - docker run -d -p 4572:4572 -p 4569:4569 -e SERVICES=dynamodb,s3  localstack/localstack
  - pip install --user awscli

script: make build verify